version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "100.118.143.9:80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wordpress
      - phpmyadmin
    networks:
      - dvwp-net

  wordpress:
    build: .
    environment:
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - "wp:/var/www/html:rw"
    networks:
      - dvwp-net

  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
    networks:
      - dvwp-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - dvwp-net

  wp-cli:
    image: "wordpress:cli-php7.1"
    environment:
      - APACHE_RUN_USER="www-data"
      - APACHE_RUN_GROUP="www-data"
    depends_on:
      - "mysql"
    volumes:
      - "wp:/var/www/html:rw"
      - "./bin/install-wp.sh:/usr/local/bin/install-wp:ro"
    networks:
      - dvwp-net

volumes:
  wp: {}
  db: {}

networks:
  dvwp-net:
    driver: bridge
